import os, json, nest_asyncio, threading, tempfile
from fastapi import FastAPI, UploadFile, Form, Request, HTTPException,Body,File
from fastapi.responses import JSONResponse
from fastapi.middleware import cors
from pydantic import BaseModel, HttpUrl,ConfigDict, Field
from pydantic.alias_generators import to_camel
from typing import Optional, List
import uvicorn
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request as GoogleAuthRequest
from googleapiclient.discovery import build
from docx import Document
import pdfplumber
import google.generativeai as genai
import logging
import json, traceback
import tempfile, os, json, time, re


# --- Basic Configuration ---
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# --- Environment Variables ---
os.environ["GOOGLE_API_KEY"] = "AIzaSyC4bqUsDLNgFwaMBLgKZcQjabNUSYuQCkg"      # <- Your Gemini key here
os.environ["NGROK_AUTHTOKEN"] = "31cnLAvDp9EM0NXsWN3Pnnpi0Nv_42XHcfVwgdG3DKQsHAiPs" # <- Your Ngrok token here

# ----------------------------
# Pydantic Models for API Response Structure
# ----------------------------
class GoogleFormResponse(BaseModel):
    success: bool
    form_url: Optional[HttpUrl] = None
    form_id: Optional[str] = None
    error: Optional[str] = None

    # Thêm cấu hình này vào
    model_config = ConfigDict(
        alias_generator=to_camel,
        populate_by_name=True, # Cho phép model hoạt động tốt với cả 2 kiểu
    )
# ----------------------------
# Configure Gemini + FastAPI + Google Forms
# ----------------------------
genai.configure(api_key=os.environ.get("GOOGLE_API_KEY"))
app = FastAPI()

# OAuth 2.0 configuration
SCOPES = ['https://www.googleapis.com/auth/forms']
creds = None

def get_google_credentials():
    global creds
    if os.path.exists('token.json'):
        creds = Credentials.from_authorized_user_file('token.json', SCOPES)
    
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(GoogleAuthRequest()) # Use aliased import to avoid conflict with FastAPI's Request
        else:
            flow = InstalledAppFlow.from_client_secrets_file(
                'credentials.json', SCOPES)
            # NOTE: For a real web app, flow.run_local_server is not ideal.
            # You should handle the redirect flow manually.
            # This redirect_uri must be registered in your Google Cloud Console credentials.
            flow.redirect_uri = "https://gemini.veronlabs.com/bot4/oauth2callback"
            creds = flow.authorize_url(port=8004)
        
        with open('token.json', 'w') as token:
            token.write(creds.to_json())
    
    return creds

# Add OAuth callback endpoint (This is for the command-line flow, might need adjustments for a web server)
@app.get("/oauth2callback")
async def oauth2callback(request: Request):
    # This endpoint is more complex to implement correctly in a production server.
    # The run_local_server method handles this for you in a local context.
    # For now, we can assume token.json is generated locally first.
    return {"message": "OAuth flow callback received. Check server logs."}


# ✅ Enable CORS
app.add_middleware(
    cors.CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ----------------------------
# ✅ SINGLE, CORRECTED Endpoint for Creating Google Forms
# ----------------------------
@app.post("/create_google_form", response_model=GoogleFormResponse)
async def create_google_form(request: Request):
    try:
        data = await request.json()
        logger.info(f"Received data for form creation")
        
        if not isinstance(data, dict) or 'questions' not in data or not data['questions']:
            raise HTTPException(status_code=400, detail="Invalid request format: 'questions' array is missing or empty.")
            
        questions = data['questions']
        
        # Get credentials
        creds = get_google_credentials()
        logger.info("Google credentials obtained successfully.")
        
        # Build the Google Forms service
        form_service = build('forms', 'v1', credentials=creds)
        
        # Create the initial form structure
        new_form = {
            'info': {
                'title': 'Multiple Choice Quiz (Generated by AI)',
                'documentTitle': 'Multiple Choice Quiz',
                'description': 'This quiz was automatically generated based on your document.'
            }
        }
        
        created_form = form_service.forms().create(body=new_form).execute()
        form_id = created_form['formId']
        
        # Prepare batch update requests for all questions
        update_requests = []
        for idx, q in enumerate(questions):
            question_text = q.get('question', f'Question {idx+1}')
            options = q.get('options', {})
            
            # Ensure all options are strings
            form_options = [
                {'value': str(options.get('A', ''))},
                {'value': str(options.get('B', ''))},
                {'value': str(options.get('C', ''))},
                {'value': str(options.get('D', ''))}
            ]
            
            update_requests.append({
                'createItem': {
                    'item': {
                        'title': question_text,
                        'questionItem': {
                            'question': {
                                'required': True,
                                'choiceQuestion': {
                                    'type': 'RADIO',
                                    'options': form_options,
                                    'shuffle': False
                                }
                            }
                        }
                    },
                    'location': {'index': idx}
                }
            })
            
        if not update_requests:
            return GoogleFormResponse(success=False, error="No valid questions were processed to add to the form.")

        # Execute the batch update to add all questions at once
        form_service.forms().batchUpdate(
            formId=form_id, 
            body={'requests': update_requests}
        ).execute()
        
        form_url = f'https://docs.google.com/forms/d/{form_id}/edit'
        logger.info(f"Form created successfully: {form_url}")
        
        return GoogleFormResponse(
            success=True,
            form_url=form_url,
            form_id=form_id
        )
        
    except Exception as e:
        logger.error(f"An error occurred while creating the Google Form: {e}", exc_info=True)
        # Return a JSON response using the Pydantic model for consistency
        return GoogleFormResponse(success=False, error=str(e))

# ----------------------------
# ✅ Utility: Extract text
# ----------------------------
def extract_text_from_pdf(file_path):
    """
    Trích xuất văn bản từ file PDF bằng pdfplumber để có kết quả tốt hơn.
    """
    text = ""
    try:
        with pdfplumber.open(file_path) as pdf:
            for page in pdf.pages:
                page_text = page.extract_text()
                if page_text:
                    text += page_text + "\n"
        # Nếu không trích xuất được gì, có thể file là ảnh scan
        if not text.strip():
            return "Không thể trích xuất văn bản từ file PDF này. File có thể là một hình ảnh được scan."
        return text
    except Exception as e:
        logger.error(f"Lỗi khi xử lý file PDF: {e}")
        # Trả về một thông báo lỗi rõ ràng
        return "Tài liệu PDF bị lỗi hoặc không thể đọc được."

def extract_text_from_docx(file_path):
    doc = Document(file_path)
    return "\n".join([para.text for para in doc.paragraphs])

# ----------------------------
# ✅ Generate MCQs with Gemini (TIẾNG VIỆT)
# ----------------------------
def generate_mcqs(text, num_questions, subject=None, grade=None, topic=None):
    model = genai.GenerativeModel("gemini-2.5-flash")

    context_info = ""
    if subject:
        context_info += f"Môn học: {subject}\n"
    if grade:
        context_info += f"Cấp học/lớp: {grade}\n"
    if topic:
        context_info += f"Chủ đề: {topic}\n"

    prompt = f"""
    Bạn là một chuyên gia giáo dục có kinh nghiệm trong việc biên soạn đề thi.
    {context_info}
    Dựa trên nội dung tài liệu, hãy tạo {num_questions} câu hỏi trắc nghiệm theo yêu cầu sau:

    1. Phân loại câu hỏi theo Bloom's Taxonomy:
        - Remember (Nhớ): 30%
        - Understand (Hiểu): 30%
        - Apply (Áp dụng): 20%
        - Analyze (Phân tích): 10%
        - Evaluate (Đánh giá): 10%

    2. Mỗi câu hỏi cần có:
        - Câu hỏi rõ ràng, súc tích
        - 4 phương án (A,B,C,D) có độ phân biệt cao
        - Đáp án đúng và giải thích chi tiết
        - Từ khóa chính và chủ đề liên quan
        - Độ khó (1-5)

    3. YÊU CẦU QUAN TRỌNG NHẤT: Phản hồi CHỈ được chứa một đối tượng JSON hợp lệ.
       KHÔNG thêm bất kỳ văn bản nào trước hoặc sau đối tượng JSON. KHÔNG sử dụng Markdown code fences (```json).
    
    Format JSON:
    {{
        "questions": [
            {{
                "id": 1,
                "question": "Câu hỏi...",
                "options": {{
                    "A": "...",
                    "B": "...",
                    "C": "...",
                    "D": "..."
                }},
                "correct_answer": "A",
                "explanation": "...",
                "difficulty": 3,
                "taxonomy": "remember",
                "keywords": ["..."],
                "topic": "..."
            }}
        ],
        "study_suggestions": ["..."],
        "references": ["..."],
        "search_terms": ["..."]
    }}
    """

    # Ghép nội dung văn bản
    full_prompt = prompt + f"\n\nNội dung tài liệu:\n{text[:10000]}"

    try:
        response = model.generate_content(full_prompt)
        raw_text = response.text.strip()
        start_index = raw_text.find('{')
        end_index = raw_text.rfind('}') + 1

        if start_index == -1 or end_index == 0:
            return {"error": "Model did not return a valid JSON object.", "raw_output": raw_text}

        json_text = raw_text[start_index:end_index]
        mcqs = json.loads(json_text)
        return mcqs

    except Exception as e:
        logger.error(f"Error generating MCQs or parsing JSON: {e}")
        return {"error": f"Model did not return valid JSON ({e})", "raw_output": getattr(response, 'text', 'No response text.')}
def generate_lesson_plan(text, subject, grade, num_periods):
    model = genai.GenerativeModel("gemini-2.5-flash")

    prompt = f"""
Bạn là một chuyên gia giáo dục phổ thông giàu kinh nghiệm, chuyên thiết kế giáo án theo công văn 5512 (trước đây là CV513/SGDĐT-GDMNPT) của Bộ GD&ĐT Việt Nam.

Dựa vào **NỘI DUNG BÀI HỌC** được cung cấp dưới đây, hãy tạo một **KẾ HOẠCH BÀI DẠY (GIÁO ÁN)** hoàn chỉnh, chi tiết và chuyên nghiệp,
phù hợp với cấp học tương ứng:
- Nếu lớp từ **6 đến 9** → soạn theo phong cách và ngôn ngữ của **bậc Trung học Cơ sở (THCS)**.
- Nếu lớp từ **10 đến 12** → soạn theo phong cách và yêu cầu năng lực của **bậc Trung học Phổ thông (THPT)**.

---

**YÊU CẦU QUAN TRỌNG:**
1. **Chỉ trả về một đối tượng JSON hợp lệ.** Không bao gồm bất kỳ văn bản nào khác, lời giải thích hay ký tự ```json.
2. Suy luận **Tên bài dạy** một cách hợp lý từ nội dung được cung cấp.
3. Các mục tiêu, học liệu, và phương pháp đánh giá phải được trình bày dưới dạng một **mảng các chuỗi** (array of strings), trong đó mỗi chuỗi tương ứng với một gạch đầu dòng.
4. Điền thông tin cho **TRƯỜNG**, **TỔ**, và **HỌ TÊN GIÁO VIÊN** bằng các giá trị mẫu hoặc giữ trống nếu chưa có.

---

**THÔNG TIN ĐẦU VÀO**

* **Môn học / Hoạt động giáo dục:** {subject}
* **Lớp:** {grade}
* **Thời gian thực hiện:** {num_periods} tiết
* **NỘI DUNG BÀI HỌC:**
    ```
    {text}
    ```

---

**CẤU TRÚC JSON ĐẦU RA BẮT BUỘC**

Hãy tuân thủ nghiêm ngặt cấu trúc JSON sau:

{{
    "lesson_plan": {{
        "header": {{
            "school": "TRƯỜNG { 'THCS' if int(grade) <= 9 else 'THPT' } ABC",
            "department": "Tổ { 'Khoa học xã hội' if subject.lower() in ['ngữ văn','lịch sử','địa lí','giáo dục công dân'] else 'Khoa học tự nhiên' }",
            "teacher_name": "(Họ và tên giáo viên)"
        }},
        "title": "(Tự suy luận từ nội dung)",
        "subject": "{subject}",
        "grade": "{grade}",
        "num_periods": {num_periods},
        "objectives": {{
            "knowledge": [
                "- (Nội dung gạch đầu dòng 1)",
                "- (Nội dung gạch đầu dòng 2)"
            ],
            "skills": [
                "- **Năng lực chung:** (Ví dụ: Tự chủ và tự học, Giao tiếp và hợp tác, Giải quyết vấn đề...)",
                "- **Năng lực đặc thù:** (Ví dụ: Năng lực ngôn ngữ, Năng lực khoa học, Năng lực thẩm mỹ...)"
            ],
            "qualities": [
                "- (Phẩm chất 1, ví dụ: Yêu nước)",
                "- (Phẩm chất 2, ví dụ: Chăm chỉ, Trách nhiệm)"
            ]
        }},
        "materials": [
            "- Giáo viên: Sách giáo khoa, máy chiếu, video clip X, phiếu học tập số 1.",
            "- Học sinh: Sách giáo khoa, vở ghi, đồ dùng học tập."
        ],
        "activities": [
            {{
                "name": "Hoạt động 1: Mở đầu (Xác định vấn đề)",
                "goal": "(Mục tiêu của hoạt động này)",
                "steps": {{
                    "assign": "(Bước 1: Giao nhiệm vụ - nội dung chi tiết)",
                    "perform": "(Bước 2: Thực hiện nhiệm vụ - nội dung chi tiết)",
                    "report": "(Bước 3: Báo cáo, thảo luận - nội dung chi tiết)",
                    "conclude": "(Bước 4: Kết luận, nhận định - nội dung chi tiết)"
                }}
            }},
            {{
                "name": "Hoạt động 2: Hình thành kiến thức mới",
                "goal": "(Mục tiêu của hoạt động này)",
                "steps": {{
                    "assign": "(Nội dung chi tiết...)",
                    "perform": "(Nội dung chi tiết...)",
                    "report": "(Nội dung chi tiết...)",
                    "conclude": "(Nội dung chi tiết...)"
                }}
            }},
            {{
                "name": "Hoạt động 3: Luyện tập",
                "goal": "(Mục tiêu của hoạt động này)",
                "steps": {{
                    "assign": "(Nội dung chi tiết...)",
                    "perform": "(Nội dung chi tiết...)",
                    "report": "(Nội dung chi tiết...)",
                    "conclude": "(Nội dung chi tiết...)"
                }}
            }},
            {{
                "name": "Hoạt động 4: Vận dụng và mở rộng",
                "goal": "(Mục tiêu của hoạt động này)",
                "steps": {{
                    "assign": "(Nội dung chi tiết...)",
                    "perform": "(Nội dung chi tiết...)",
                    "report": "(Nội dung chi tiết...)",
                    "conclude": "(Nội dung chi tiết...)"
                }}
            }}
        ],
        "assessment": [
            "- **Hình thức:** Quan sát, vấn đáp, sản phẩm nhóm, bài viết ngắn.",
            "- **Công cụ:** Phiếu học tập, câu hỏi trắc nghiệm, thang đo thái độ.",
            "- **Tiêu chí:** (Nêu rõ các tiêu chí đánh giá cho từng hoạt động hoặc sản phẩm)"
        ]
    }}
}}
"""

    try:
        response = model.generate_content(prompt)
        raw = response.text.strip()
        start = raw.find('{')
        end = raw.rfind('}') + 1
        json_text = raw[start:end]
        return json.loads(json_text)
    except Exception as e:
        return {"error": str(e), "raw_output": getattr(response, 'text', '')}

# ----------------------------
# ✅ FastAPI Endpoint for Generating MCQs
# ----------------------------
@app.post("/generate_mcqs")
async def generate_mcqs_endpoint(
    file: UploadFile = Form(...),
    num_questions: int = Form(...),
    subject: str = Form(None),
    grade: str = Form(None),
    topic: str = Form(None)
):
    # 🕐 Bắt đầu đo thời gian xử lý
    start_time = time.time()

    with tempfile.NamedTemporaryFile(delete=False, suffix=file.filename) as temp_file:
        temp_path = temp_file.name
        content = await file.read()
        temp_file.write(content)

    try:
        # 🧾 Đọc nội dung file
        if file.filename.endswith(".pdf"):
            text = extract_text_from_pdf(temp_path)
        elif file.filename.endswith(".docx"):
            text = extract_text_from_docx(temp_path)
        else:
            raise HTTPException(status_code=400, detail="Unsupported file type. Please upload a PDF or DOCX file.")

        if not text.strip():
            raise HTTPException(status_code=400, detail="No text extracted from document.")

        # 🤖 Gọi model sinh câu hỏi
        mcq_result = generate_mcqs(text, num_questions=num_questions, subject=subject, grade=grade, topic=topic)


        end_time = time.time()
        response_payload = {
            "success": True,
            "provider": "Google Gemini",
            "model": "gemini-2.5-flash",
            "processing_time": round(end_time - start_time, 2),
            "subject": subject,
            "grade": grade,
            "topic": topic,
            "num_questions": num_questions,
            "questions": mcq_result.get("questions", []),
            "study_suggestions": mcq_result.get("study_suggestions", []),
            "references": mcq_result.get("references", []),
            "search_terms": mcq_result.get("search_terms", []),
        }

        return JSONResponse(content=response_payload, status_code=200)

    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error generating MCQs: {str(e)}")

    finally:
        os.remove(temp_path)
@app.post("/generate_lesson_plan")
async def generate_lesson_plan_endpoint(
    # ✅ Sử dụng Form thay cho Body để nhận multipart/form-data
    subject: str = Form(..., description="Tên môn học"),
    grade: str = Form(..., description="Lớp"),
    num_periods: int = Form(1, description="Số tiết"),
    
    # ✅ Cho phép cả hai dạng input là tùy chọn
    text: Optional[str] = Form(None, description="Nội dung bài học dạng văn bản"),
    file: Optional[UploadFile] = File(None, description="File nội dung bài học (.pdf, .docx)")
):
    if not text and not file:
        raise HTTPException(status_code=400, detail="Bạn phải cung cấp nội dung dạng text hoặc upload một file.")

    temp_path = None
    try:
        lesson_content = ""
        if file:
            with tempfile.NamedTemporaryFile(delete=False, suffix=os.path.splitext(file.filename)[1]) as temp_file:
                temp_path = temp_file.name
                content = await file.read()
                temp_file.write(content)
            
            file_extension = os.path.splitext(file.filename)[1].lower()
            
            if file_extension == ".pdf":
                lesson_content = extract_text_from_pdf(temp_path)
            elif file_extension == ".docx":
                lesson_content = extract_text_from_docx(temp_path)
            else:
                 raise HTTPException(status_code=400, detail="Định dạng file không được hỗ trợ. Vui lòng tải lên file PDF hoặc DOCX.")
            
            if not lesson_content or "Không thể trích xuất" in lesson_content or "Tài liệu PDF bị lỗi" in lesson_content:
                raise HTTPException(status_code=400, detail=lesson_content)
        
        elif text:
            lesson_content = text

        logger.info(f"Nội dung bài học đã sẵn sàng để tạo giáo án ({len(lesson_content)} ký tự).")
        
        result = generate_lesson_plan(lesson_content, subject, grade, num_periods)

        if "error" in result:
            raise HTTPException(status_code=500, detail=f"Lỗi từ Gemini: {result.get('error')}")

        return JSONResponse(content=result, status_code=200)

    except HTTPException as http_exc:
        raise http_exc
    except Exception as e:
        logger.error(f"Lỗi không xác định khi tạo giáo án: {e}", exc_info=True)
        return JSONResponse(
            content={
                "error": str(e),
                "trace": traceback.format_exc()
            },
            status_code=500
        )
    finally:

        if temp_path and os.path.exists(temp_path):
            os.remove(temp_path)
            logger.info(f"Đã xóa file tạm: {temp_path}")
# ----------------------------
# ❌ COMMENTED OUT - This endpoint is incomplete as its helper functions are not defined.
# ----------------------------
# @app.post("/analyze")
# async def analyze_document(file: UploadFile):
#     # The following functions are not defined in the script:
#     # extract_text, generate_summary, extract_concepts, assess_difficulty, suggest_topics
#     
#     # # Extract text
#     # text = await extract_text(file)
#     # 
#     # # Analyze document structure and content
#     # analysis = {
#     #     "summary": generate_summary(text),
#     #     "key_concepts": extract_concepts(text),
#     #     "difficulty_level": assess_difficulty(text),
#     #     "recommended_topics": suggest_topics(text)
#     # }
#     # 
#     # return JSONResponse(analysis)
#     raise HTTPException(status_code=501, detail="Endpoint not implemented.")

# --- Main Execution ---
def run_app():
    # nest_asyncio.apply() # May be needed in environments like Jupyter/Colab
    uvicorn.run(app, host="0.0.0.0", port=8004)

if __name__ == "__main__":
    run_app()